---
# CERTIFICAT
cn_root_ca: Tips-of-mine
c: FR
st: Nord
l: Roubaix
expiry: 8767h
rotate_certs_pki: false
rotate_full_pki: false

# Version des Composents a installer
release_etcd: v3.4.3
release_k8s: v1.17.3
k8s_delete_present: False
etcd_delete_present: False
etcd_check_present: True

# Configuration reseau
domaine: exemple.lan
cluster_cidr: 10.59.0.0/16
service_cluster_ip_range: 10.62.0.0/24
k8s_service: 10.62.0.1
cluster_dns_ip: 10.62.0.10
service_node_port_range: 30000-32767
k8s_proxy_mode: ipvs
k8s_proxy_ipvs_algotithm: rr

# Personnalisation des modules
engine: docker
network_plugin: flannel
flannel_iface: default
ingress_controller: traefik
dns_server_soft: coredns
populate_etc_hosts: yes
k8s_dashboard: True
service_mesh: linkerd
linkerd_release: stable-2.6.0
install_helm: false
init_helm: false

# Calico
calico_mtu: 1440

# Security
encrypt_key_etcd: 1fJcKt6vBxMt+AkBanoaxFF2O6ytHIkETNgQWv4b/+Q=

# Data Directory
data_path: "/opt/agorakube"
etcd_data_directory: "/var/lib/etcd"
#restoration_snapshot_file: /path/snopshot/file Located on {{ etcd_data_directory }}
