---
- name: check if certs exist
  stat:
    path: "{{ data_path }}/certificates/"
  register: cert_check
- name: Delete existing certs and kubeconfig files
  file:
    path: "{{ data_path }}/certificates/"
    state: absent
  when: cert_check.stat.exists
