---
- name: Install gcc
  package:
    name: gcc
    state: latest

# Git is required for the Install cfssl task, Centos does not come with git installed
- name: Install git
  package:
    name: git
    state: latest
- name: Install cfssl
  shell: source /etc/profile && go get -u github.com/cloudflare/cfssl/cmd/cfssl
  args:
    creates: /usr/local/bin/cfssl
    executable: /bin/bash
  environment:
    GOPATH: /usr/local
- name: Install cfssljson
  shell: source /etc/profile && go get -u github.com/cloudflare/cfssl/cmd/cfssljson
  args:
    creates: /usr/local/bin/cfssljson
    executable: /bin/bash
  environment:
    GOPATH: /usr/local
