---
- name: Install cfssl and cfssljson
  include_tasks: install-cfssl-cfssljson.yaml
- name: clean certs
  include_tasks: clean-certs.yaml
  when: update_certs
- name: generate certificates and configs
  include_tasks: gen-certs.yaml

