---
- name: Ajout des cgroups dans cmdline.txt
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: true
    regexp: '^(.*rootwait)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    
- name: désactivation du swap
  shell: swapoff -a && dphys-swapfile swapoff && dphys-swapfile uninstall && update-rc.d dphys-swapfile remove
  ignore_errors: True

- name: Installer des logiciels pour l'approvisionnement et le dépannage
  apt:
    name:
      - net-tools
      - openssl
      - rsync
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: yes

- name: Add apt key for kubectl
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
    
- name: Ajout repository [deb https://apt.kubernetes.io/ kubernetes-xenial main]
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present