---
- name: Installation haproxy
  apt:
    name:
      - haproxy
    state: present
    update_cache: yes

- name: Configuration haproxy
  template:
    src: /templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    owner: pi
    group: pi

- name: Demarrage et activation du service haproxy
  service:
    name: haproxy
    state: started
    enabled: yes
