---
- name: Verifiez le nombre de KMASTER(S)
  fail:
    msg: "Sur les KMASTER {{ MASTER_NUM }} - Le nombre de KMASTER DOIT être de 1, 3, 5 ou 7, et DEVRAIT être de 3 ou 5."
  when: KMASTER_NUM not in ['1','3','5','7']
  
- name: Verifiez le nombre de ETCD
  fail:
    msg: "Sur les serveurs ETCD {{ ETCD_NUM }} - Le nombre de serveur ETCD DOIT être de 1,3,5 or 7, et DEVRAIT être de 3 ou 5."
  when: ETCD_NUM not in ['1','3','5','7']
  
- name: Verifiez le nombre de KWORKER(S)
  fail:
    msg: "Sur les KWORKER {{ WORKER_NUM }} - Vous devez avoir au moins 1 KWORKER."
  when: KWORKER_NUM == '0'
