---
# This role installs and sets up keepalived

- name: Ricavo IP Master
  set_fact:
    keepalived_master_ip: "{{ play_hosts|map('extract', hostvars,['ansible_eth0','ipv4','address'])|list|sort(reverse=true)|first }}"

- name: Voir IP KMaster
  debug:
    var: keepalived_master_ip
  run_once: true

- name: Installation keepalived
  apt: name=keepalived state=latest cache_valid_time=86400 update_cache=yes
  tags: keepalived
  notify: restart keepalived

- name: Configuration de keepalived
  template: 
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
    owner: pi
    group: pi
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=started
  tags: keepalived
