---
- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - 101-check-hosts
    - 102-hostname
    - 103-fichier-hosts
    
- hosts: kmaster01
  become: true
  roles:
    - 201-compliance-checks
    - 202-pre-requis