---
- name: Create /root/.kube directory
  file:
    path: /root/.kube
    state: directory
- name: Inject Kubeconfig
  copy:
    src: "{{ data_path }}/certificates/configs/admin/admin.conf"
    dest: /root/.kube/config
