---
- name: Download etcd binaries
  unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/{{etcd_release}}/etcd-{{etcd_release}}-linux-amd64.tar.gz
    dest: /usr/bin
    remote_src: yes

- name: create folder /var/lib/etcd
  file: 
    path: /var/lib/etcd
    state: directory

- name: Import etcd.service
  template:
    src: etcd.service.j2 
    dest: /etc/systemd/system/etcd.service
  notify:
    - Reload daemons
    - Restart etcd    
    
- name: Run etcd
  systemd:
    state: started
    daemon_reload: yes
    name: etcd
    enabled: yes
