---

# Variables for role keepalived

keepalived_auth_pass: "1111"
keepalived_router_id: "52"
keepalived_shared_iface: "eth0"
keepalived_shared_ip: "192.168.1.200"
keepalived_check_process: "keepalived"
keepalived_priority: "100"
keepalived_backup_priority: "50"
