---
- name: Add Docker repository for {{ ansible_distribution }}
  include_tasks: "repo-{{ ansible_distribution }}.yaml"

- name: Install Docker for {{ ansible_distribution }}
  include_tasks: "docker-{{ ansible_distribution }}.yaml"

- name: Create /etc/cni/net.d/ directory
  file:
    path: /etc/cni/net.d
    state: directory
    recurse: yes
    
- name: Push /etc/cni/net.d/99-loopback.conf
  copy:
    src: 99-loopback.conf
    dest: /etc/cni/net.d/99-loopback.conf
  notify:
    - restart docker
  
- name: Create /opt/cni/bin/ directory
  file:
    path: /opt/cni/bin/
    state: directory

- name: Download CNI 0.8.1
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v0.8.1/cni-plugins-linux-amd64-v0.8.1.tgz
    dest: /opt/cni/bin/
    remote_src: yes
    creates: /opt/cni/bin/bridge
  notify:
    - restart docker

- name: Start Runtime
  systemd:
    state: started
    name: docker

- name: Configure /etc/docker/daemon.json
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json
  notify:
    - Reload docker

- name: Create /etc/systemd/system/docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes

- name: Make sure docker is running
  systemd:
    state: started
    name: docker
