---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: coredns
  register: coredns_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ coredns_tempdir.path }}/coredns.yaml"
    src: "../templates/coredns.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf apply -f {{ coredns_tempdir.path }}/coredns.yaml
  register: apply_coredns
  changed_when: >
    apply_coredns.stdout is search("created")
    or apply_coredns.stdout is search("configured")

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ coredns_tempdir.path }}"
  changed_when: false
