---
- name: Sauvegarde des fichiers /etc/hosts
  copy:
    src: /etc/hosts
    dest: /etc/hosts.backup
    owner: pi
    group: pi
    mode: '0644'
    backup: yes
    
- name: Ecriture dans le fichier /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    create: yes
  with_items:
  - "{{ groups['all'] }}"
