---
- name: restart containerd
  systemd:
    state: restarted
    name: containerd

- name: Reload docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    
- name: restart docker
  systemd:
    state: restarted
    name: docker